### ISSUE TITLE
compiling error?

### ISSUE THREAD

**Issue by hahaxdxd** [BadDeathclaw/bad-deathclaw#86]
code\game\gamemodes\wizard\soulstone.dm:106:error unexpected var or proc name after . operator

**Comment by xxxnoscopexx** [comment]
yeah I was getting the same error though I do not know how to fix it

**Comment by Polyushko** [comment]
I have the same problem, there is a way to adjust this?

**Comment by Digdugxx** [comment]
It's your byond version dummies. I can't remember exactly which one it runs on but I know it's not beta
