### ISSUE TITLE
Overseer can abuse Job Management to deny all other roles

### ISSUE THREAD

**Issue by rhicora** [BadDeathclaw/bad-deathclaw#90]
An evil Overseer could deny all Legion, NCR, BoS, and Wastelander jobs thus making all latejoiners his slaves.

![image](https://user-images.githubusercontent.com/37093159/45944302-91673c00-bf9e-11e8-9344-576258d2d88e.png)

**Comment by ma44** [comment]
Pretty solved so may as well close this legacy issue
